apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  labels:
    app: analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-api
  template:
    metadata:
      labels:
        app: analytics-api
    spec:
      containers:
        - name: analytics-api
          image: "registry.sXXXXXXX-at-student-dhbw-mannheim-de.users.dhbw.site/analytics-api:latest"
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: POSTGRES_HOST
              value: "analytics-db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: analytics-db-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: analytics-db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-db-credentials
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
