apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: translation-api
  labels:
    app: translation-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: translation-api
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
